name: EndlessEnchant
version: 3.3
author: Drkmaster83
main: me.Drkmaster83.EndlessEnchant.EndlessEnchant
commands:
  EndlessEnchant:
    description: The base command for EndlessEnchant.
    aliases: [ee, enchant]
